[package]
name = "regis"
version = "0.1.0"
authors = ["Jake <jake@boxed.email>"]
edition = "2018"

[dependencies]
indexmap = "1.6.1"
lazy_static = "1.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"
uuid = { version = "0.8.1", features = ["v4"] }
itertools = "0.9.0"
