use crate::shared::SharedImmutable;

use super::procedure::Procedure;
use super::ExportLocation;

#[derive(Debug)]
pub enum Instruction {
    Blank,
    Pop,
    Duplicate,
    DuplicateTop(usize),
    JumpIf(usize),
    JumpUnless(usize),
    Jump(usize),
    Return,
    IsNull,
    PushNull,
    PushBoolean(bool),
    PushInt(i64),
    PushFloat(f64),
    PushString(SharedImmutable<String>),
    PushVariable(usize),
    AssignVariable(usize),
    PushExport(Box<ExportLocation>),
    AssignExport(Box<ExportLocation>),
    PushGlobal(usize),
    CreateList(usize),
    CreateObject(usize),
    CreateFunction(SharedImmutable<Procedure>),
    Call(usize),
    BinaryAdd,
    BinaryDiv,
    BinaryMul,
    BinarySub,
    BinaryGt,
    BinaryLt,
    BinaryGte,
    BinaryLte,
    BinaryEq,
    BinaryNeq,
    GetIndex,
    SetIndex,
    Push,
    Echo,
}
